lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models

# Create your models here.
class List(models.Model):
	pass

class Item(models.Model):
	angka = models.IntegerField(default=0)
	angkaacak = models.IntegerField(default=0)
	statusnya = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from lists.models import Item, List
import random

# # Create your views here.
def home_page(request):
    return render(request, 'home.html')
def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    comment = tambahComment(list_)
    return render(request, 'list.html', {'list': list_, 'comment': comment})

def new_list(request):
    list_ = List.objects.create()
    n = random.randint(1,30)
    text=request.POST['item_text']
    x = int(text)
    item = Item()
    item.angka = x
    item.angkaacak = n
    item.statusnya = status(x, n)
    item.list = list_
    item.save()
    return redirect('/lists/%d/' % (list_.id,))

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    n = random.randint(1,30)
    text=request.POST['item_text']
    x = int(text)
    item = Item()
    item.angka = x
    item.angkaacak = n
    item.statusnya = status(x, n)
    item.list = list_
    item.save()
    return redirect('/lists/%d/' % (list_.id,))

def status(x, y):
	if x < y+3 and x > y-3:
		return 'Kamu menang!!'
	else:
		return 'Kamu kalah!!'

def tambahComment(list_id):
    list_temp = Item.objects.filter(list=list_id).reverse()
    counter = 0
    comment = ''

    if len(list_temp) < 3:
        return comment

    for i in range(3):
        item=list_temp[i]
        if item.statusnya == 'Kamu menang!!':
            counter = counter+1

    if counter==3:
        comment='Ulala!!'

    if len(list_temp) < 5:
        return comment

    counter = 0

    for i in range(5):
        item=list_temp[i]
        if item.statusnya == 'Kamu menang!!':
            counter = counter+1

    if counter==5:
        comment='Ulalala'

    if len(list_temp) < 10:
        return comment

    counter = 0

    for i in range(10):
        item=list_temp[i]
        if item.statusnya == 'Kamu menang!!':
            counter = counter+1

    if counter==10:
        comment='Uulala'

    return comment

lists/templates/home.html
<html>
	<head>
		<title>Game Tebak Angka</title>
	</head>
	<body>
		<h1>Game Tebak Angka</h1>
		<form method="POST" action="/lists/new">
			<input name="item_text" id="id_new_item" placeholder="Masukkan angka 1-30" />
			{% csrf_token %}
		</form>
<!-- 
		<span>{{ comment }}</span> -->
		
		<table id="id_list_table">
			<!--Membuat multiple display list-->
			{% for item in items %}
				<tr><td> {{ forloop.counter }}: {{ item.text }}</td></tr>
			{% endfor %}
		</table>
	</body>
</html>

lists/templates/list.html
<html>
	<head>
		<title>Game Tebak Angka</title>
	</head>
	<body>
		<h1>Game Tebak Angka</h1>
		<form method="POST" action="/lists/{{ list.id }}/add_item">
			<input name="item_text" id="id_new_item" placeholder="Masukkan angka 1-30" />
			{% csrf_token %}
		</form>
		<table id="id_list_table">
			{% for item in list.item_set.all %}
            	<tr>
            		<td>Angka: {{ item.angkaacak }}</td>
            		<td>Tebakan: {{ item.angka }}</td>
            	</tr>
            	<tr>
            		<td>{{ item.statusnya }}</td>
            	</tr>
            	<tr>
            		<td>{% block comment_text %} {{ comment }} {% endblock %}</td>
            	</tr>
        	{% endfor %}
		</table>
	</body>
</html>